# Generated by Django 5.2.8 on 2025-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男"), ("female", "女")],
                max_length=10,
                null=True,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="手机号"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="单位/学校"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="学号/工号"
            ),
        ),
    ]
