# nginx server config for iclass

server {
    # Listen on the standard HTTP port 80
    listen 80;
    server_name iclass.com;

    include mime.types;

    # The root directory for the frontend application.
    root /Users/keke/iclass/frontend/dist;
    index index.html;

    # Location for the API.
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/tmp/gunicorn.sock;
    }

    # Location for media files.
    location /media/ {
        alias /Users/keke/iclass/media/;
    }

    # Location for static files.
    location /static/ {
        alias /Users/keke/iclass/staticfiles/;
    }

    # For everything else, serve the frontend application.
    # This is necessary for single-page applications with client-side routing.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
