# Generated by Django 5.2.9 on 2026-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interaction", "0003_randomquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
    ]
