# Generated by Django 5.2.9 on 2026-01-04 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interaction", "0004_vote_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voteresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="voteresponse",
            name="vote",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="interaction.vote",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voteresponse",
            unique_together={("vote", "student")},
        ),
    ]
