# Generated by Django 5.2.9 on 2026-01-06 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "interaction",
            "0005_alter_voteresponse_unique_together_voteresponse_vote_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="randomquestion",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "进行中"), ("finished", "已结束")],
                default="ongoing",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="randomquestion",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="randomly_questioned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被提问学生",
            ),
        ),
    ]
