# Generated by Django 5.2.9 on 2025-12-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0004_chapter_parent_chapter_pdf_chapter_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("due_date", models.DateTimeField(verbose_name="截止日期")),
                (
                    "time_limit",
                    models.PositiveIntegerField(default=60, verbose_name="考试时长(分钟)"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="问题文本")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "单选题"),
                            ("multiple_choice", "多选题"),
                            ("true_false", "判断题"),
                            ("fill_in_the_blank", "填空题"),
                            ("short_answer", "简答题"),
                        ],
                        max_length=20,
                        verbose_name="问题类型",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0, verbose_name="分值")),
                (
                    "correct_answer",
                    models.TextField(blank=True, null=True, verbose_name="正确答案"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="所属考试",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="选项文本")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否为正确答案"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="exams.examquestion",
                        verbose_name="所属问题",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="提交时间"),
                ),
                ("grade", models.FloatField(blank=True, null=True, verbose_name="分数")),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="教师评语"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taking", "正在进行"),
                            ("submitted", "已提交"),
                            ("graded", "已批改"),
                        ],
                        default="taking",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="exams.exam",
                        verbose_name="所提交的考试",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交学生",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="答案文本")),
                ("score", models.FloatField(blank=True, null=True, verbose_name="得分")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.examquestion",
                        verbose_name="所回答的问题",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.examsubmission",
                        verbose_name="所属提交记录",
                    ),
                ),
            ],
        ),
    ]
