# Generated by Django 5.2.9 on 2025-12-23 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_remove_exam_due_date_exam_end_time_exam_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examsubmission",
            unique_together={("exam", "student")},
        ),
    ]
