# Generated by Django 5.2.9 on 2025-12-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_alter_examsubmission_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examanswer",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="exams.examquestion",
                verbose_name="所回答的问题",
            ),
        ),
    ]
