# Generated by Django 5.2.8 on 2025-12-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="章节标题")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="章节内容"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="章节顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
