# Generated by Django 5.2.8 on 2025-12-10 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursematerial",
            name="title",
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="资料名称"),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="size",
            field=models.BigIntegerField(default=0, verbose_name="文件大小"),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_materials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
    ]
