# Generated by Django 5.2.9 on 2025-12-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_coursematerial_title_coursematerial_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="courses.chapter",
                verbose_name="父章节",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="chapter_pdfs/", verbose_name="章节PDF"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="chapter_videos/", verbose_name="章节视频"
            ),
        ),
    ]
