# Generated by Django 5.2.9 on 2025-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_chapter_parent_chapter_pdf_chapter_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="课程封面"
            ),
        ),
    ]
