# Generated by Django 5.2.9 on 2025-12-30 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_course_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
    ]
