# Generated by Django 5.2.9 on 2025-12-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="score",
            field=models.FloatField(blank=True, null=True, verbose_name="得分"),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(default=0, verbose_name="分值"),
        ),
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="教师评语"),
        ),
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[("submitted", "已提交"), ("graded", "已批改")],
                default="submitted",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "选择题"),
                    ("true_false", "判断题"),
                    ("fill_in_the_blank", "填空题"),
                    ("short_answer", "简答题"),
                ],
                max_length=20,
                verbose_name="问题类型",
            ),
        ),
    ]
