# Generated by Django 5.2.9 on 2025-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assignments",
            "0002_answer_score_question_points_submission_feedback_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(blank=True, null=True, verbose_name="正确答案"),
        ),
    ]
