# Generated by Django 5.2.9 on 2025-12-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_question_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "单选题"),
                    ("multiple_choice", "多选题"),
                    ("true_false", "判断题"),
                    ("fill_in_the_blank", "填空题"),
                    ("short_answer", "简答题"),
                ],
                max_length=20,
                verbose_name="问题类型",
            ),
        ),
    ]
