# Generated by Django 5.2.9 on 2025-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkinrecord",
            options={"verbose_name": "签到记录", "verbose_name_plural": "签到记录"},
        ),
        migrations.AddField(
            model_name="checkinrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "出勤"),
                    ("late", "迟到"),
                    ("absent", "缺勤"),
                    ("sick_leave", "病假"),
                    ("personal_leave", "事假"),
                    ("official_leave", "公假"),
                ],
                default="present",
                max_length=20,
                verbose_name="签到状态",
            ),
        ),
        migrations.AlterField(
            model_name="checkinrecord",
            name="checkin_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="签到时间"),
        ),
        migrations.AlterField(
            model_name="checkinrecord",
            name="is_manual",
            field=models.BooleanField(default=False, verbose_name="是否为手动操作"),
        ),
    ]
