# Generated by Django 5.2.9 on 2025-12-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0002_alter_checkinrecord_options_checkinrecord_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "出勤"),
                    ("late", "迟到"),
                    ("absent", "缺勤"),
                    ("sick_leave", "病假"),
                    ("personal_leave", "事假"),
                ],
                default="present",
                max_length=20,
                verbose_name="签到状态",
            ),
        ),
    ]
