# Generated by Django 5.0.6 on 2026-01-12 17:40

from django.db import migrations

def update_notification_messages(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Questionnaire = apps.get_model('feedback', 'Questionnaire')

    try:
        questionnaire_ct = ContentType.objects.get_for_model(Questionnaire)
        notifications_to_update = Notification.objects.filter(content_type=questionnaire_ct)

        for notification in notifications_to_update:
            if '问卷' in notification.message:
                notification.message = notification.message.replace('问卷', '反馈')
                notification.save()
    except ContentType.DoesNotExist:
        # 如果在测试环境中没有 feedback 应用，这可以防止迁移失败
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        # 确保 feedback 应用的迁移在此之前运行
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_notification_messages),
    ]
